import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, RefreshCw, Tv } from "lucide-react";
import { useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { invokeCmd } from "@/shared/api/tauri";
import { ErrorState } from "@/shared/components/ErrorState";
import { useSettingsStore } from "@/shared/stores/settingsStore";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { IptvPlayer } from "./IptvPlayer";
import { iptvHomePath, iptvReturnPathFromState } from "./iptvRoute";
import { builtInSources, isHttpUrl, playlistSourceFromRoute } from "./playlistSource";
import type { IptvChannel } from "./types";

type IptvPlayerTopBarProps = {
  title: string;
  sourceLabel: string;
  group: string | null;
  reconnectEnabled: boolean;
  onBack: () => void;
  onReconnect: () => void;
};

function IptvPlayerTopBar({
  title,
  sourceLabel,
  group,
  reconnectEnabled,
  onBack,
  onReconnect,
}: IptvPlayerTopBarProps) {
  return (
    <header className="relative flex h-11 shrink-0 items-center justify-center border-b border-border/80 bg-sidebar/90 px-3">
      <Tooltip>
        <TooltipTrigger
          render={
            <Button
              variant="ghost"
              size="icon-sm"
              className="absolute left-3 rounded-lg transition-transform hover:-translate-x-0.5 hover:bg-muted/70"
              aria-label="返回频道列表"
              onClick={onBack}
            />
          }
        >
          <ChevronLeft data-icon="inline-start" aria-hidden />
        </TooltipTrigger>
        <TooltipContent>返回频道列表</TooltipContent>
      </Tooltip>

      <div className="absolute inset-x-12 flex min-w-0 items-center justify-center px-12">
        <div className="min-w-0 text-center">
          <p
            className="truncate text-sm font-semibold tracking-tight text-foreground/90"
            title={title}
          >
            {title}
          </p>
          <p className="hidden truncate text-xs text-muted-foreground sm:block" title={sourceLabel}>
            {sourceLabel}
          </p>
        </div>
      </div>

      <div className="absolute right-3 flex items-center gap-1.5">
        {group && (
          <Badge variant="outline" className="hidden max-w-28 truncate md:inline-flex">
            {group}
          </Badge>
        )}
        <Tooltip>
          <TooltipTrigger render={<span className="inline-flex" />}>
            <Button
              variant="ghost"
              size="sm"
              disabled={!reconnectEnabled}
              aria-label="重新连接频道"
              onClick={onReconnect}
            >
              <RefreshCw data-icon="inline-start" aria-hidden />
              <span className="hidden sm:inline">重连</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>重新连接频道</TooltipContent>
        </Tooltip>
      </div>
    </header>
  );
}

function PlayerPageState({ children }: { children: React.ReactNode }) {
  return (
    <main className="flex min-h-0 flex-1 items-center justify-center overflow-auto bg-background p-4 md:p-6">
      <div className="w-full max-w-xl">{children}</div>
    </main>
  );
}

export function IptvPlayerPage() {
  const [searchParams] = useSearchParams();
  const location = useLocation();
  const navigate = useNavigate();
  const [reloadToken, setReloadToken] = useState(0);
  const iptvCustomM3uUrl = useSettingsStore((state) => state.iptvCustomM3uUrl);

  const sourceId = searchParams.get("source");
  // Keep accepting links generated by older builds, but new custom sources
  // resolve from the private, device-local settings value.
  const customSourceUrl = searchParams.get("m3u") ?? iptvCustomM3uUrl;
  const sourceIsValid =
    sourceId === null ||
    builtInSources.some((candidate) => candidate.id === sourceId) ||
    (sourceId === "custom" && isHttpUrl(customSourceUrl));
  const source = playlistSourceFromRoute(sourceId, customSourceUrl);
  const requestedChannelUrl = searchParams.get("channel");
  const channelUrl = isHttpUrl(requestedChannelUrl) ? requestedChannelUrl : null;
  const group = searchParams.get("group");
  const query = searchParams.get("q");
  const homePath = iptvHomePath({ source, group, query });
  const returnPath = iptvReturnPathFromState(location.state) ?? homePath;

  const playlistQuery = useQuery({
    queryKey: ["iptv_playlist", source.url],
    queryFn: () => invokeCmd<IptvChannel[]>("iptv_load_playlist", { sourceUrl: source.url }),
    enabled: channelUrl !== null && sourceIsValid,
    staleTime: 5 * 60_000,
    gcTime: 15 * 60_000,
  });
  const channel = useMemo(() => {
    if (!channelUrl) return null;
    return playlistQuery.data?.find((candidate) => candidate.url === channelUrl) ?? null;
  }, [channelUrl, playlistQuery.data]);

  const title = channel?.name ?? "IPTV 播放器";
  const channelGroup = channel?.group || group;

  function goBack() {
    // The state helper accepts only local IPTV discovery paths. Replacing this
    // route prevents a browser Back action from immediately reopening playback.
    navigate(returnPath, { replace: true });
  }

  const topBar = (
    <IptvPlayerTopBar
      title={title}
      sourceLabel={source.label}
      group={channelGroup}
      reconnectEnabled={channel !== null}
      onBack={goBack}
      onReconnect={() => setReloadToken((token) => token + 1)}
    />
  );

  if (!channelUrl || !sourceIsValid) {
    return (
      <div className="flex h-full min-h-0 flex-col bg-background">
        {topBar}
        <PlayerPageState>
          <ErrorState
            error={
              new Error(
                !sourceIsValid
                  ? "频道源无效或缺少自定义 M3U 地址。请从 IPTV 首页重新选择频道。"
                  : "缺少有效的频道地址。请从 IPTV 首页选择频道。",
              )
            }
            title="无效的 IPTV 播放链接"
          />
        </PlayerPageState>
      </div>
    );
  }

  if (playlistQuery.isPending) {
    return (
      <div className="flex h-full min-h-0 flex-col bg-background">
        {topBar}
        <PlayerPageState>
          <div className="flex min-h-40 flex-col items-center justify-center gap-3 text-sm text-muted-foreground">
            <Spinner className="size-6 text-primary" aria-label="正在加载频道" />
            <p>正在读取频道列表…</p>
          </div>
        </PlayerPageState>
      </div>
    );
  }

  if (playlistQuery.isError) {
    return (
      <div className="flex h-full min-h-0 flex-col bg-background">
        {topBar}
        <PlayerPageState>
          <ErrorState
            error={playlistQuery.error}
            title="IPTV 频道列表加载失败"
            onRetry={() => void playlistQuery.refetch()}
          />
        </PlayerPageState>
      </div>
    );
  }

  if (!channel) {
    return (
      <div className="flex h-full min-h-0 flex-col bg-background">
        {topBar}
        <PlayerPageState>
          <ErrorState
            error={new Error("该频道已不在当前列表中，可能已被频道源更新或移除。")}
            title="找不到请求的频道"
            onRetry={() => void playlistQuery.refetch()}
          />
        </PlayerPageState>
      </div>
    );
  }

  return (
    <div className="flex h-full min-h-0 flex-col bg-background">
      {topBar}
      <main className="flex min-h-0 flex-1 flex-col bg-black">
        <div className="flex min-h-0 flex-1 items-center justify-center p-3 md:p-5">
          <div className="aspect-video h-full max-h-full max-w-full">
            <IptvPlayer channel={channel} reloadToken={reloadToken} />
          </div>
        </div>
        <footer
          data-slot="iptv-player-footer"
          className="flex shrink-0 flex-wrap items-center gap-2 border-t border-border/80 bg-sidebar/90 px-3 py-2"
        >
          <Badge variant="outline">{source.label}</Badge>
          {channel.group && <Badge variant="secondary">{channel.group}</Badge>}
          <p className="min-w-0 flex-1 text-xs text-muted-foreground">
            仅观看你所在地允许访问、且你有权使用的频道。
          </p>
          <Tv className="size-4 shrink-0 text-muted-foreground" aria-hidden />
        </footer>
      </main>
    </div>
  );
}
