[package]
name = "tauri-plugin-player-gesture"
version = "0.1.0"
description = "Android application brightness and media-volume controls for rLive player gestures"
edition = "2024"
links = "tauri-plugin-player-gesture"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
tauri = { version = "2", features = [] }
